-- Restore correct exercise trackingType, corrupted by the malformed v2 re-import.
-- The 'exercises_reimport_MERGED_v2.csv' had unquoted commas + no row breaks, so the
-- Tracking Style column imported as garbage, which made the app hide the weight field
-- (it checks for the exact string 'Weight & Reps'). Source: clean exercises_reimport_MERGED.csv.
-- Updates every user's copy of each exercise by id. Run once in the Supabase SQL Editor.

update public.exercises as e
set "trackingType" = v.tt
from (values
  ('get-ups','Weight & Reps'),
  ('single-leg-negative-extensions','Weight & Reps'),
  ('bb-pendlay-row','Weight & Reps'),
  ('kb-horn-curls','Weight & Reps'),
  ('high-glute-mobilisation','Time Only'),
  ('pelvic-bowl-mobilisation','Time Only'),
  ('anterior-neck-mobilisation','Time Only'),
  ('basic-first-rib-smash-floss','Time Only'),
  ('bb-anterior-shoulder-sheer','Time Only'),
  ('banded-hamstring-stretch','Time Only'),
  ('hip-wheel','Time Only'),
  ('banded-deadlifts','Weight & Reps'),
  ('plank-circuit','Weight & Reps, Time Only'),
  ('sumo-squat-bw','Weight & Reps'),
  ('burpees-belly-to-floor','Weight & Reps'),
  ('ski-abs','Weight & Reps, Time Only'),
  ('dumbbell-squats','Weight & Reps, Time Only'),
  ('wide-db-chest-press','Weight & Reps'),
  ('bicep-curl','Weight & Reps'),
  ('bulgarian-split-squat','Weight & Reps'),
  ('db-squat-jumps','Weight & Reps'),
  ('bb-deadlift','Weight & Reps'),
  ('burpees','Weight & Reps'),
  ('bw-single-leg-deadlift','Weight & Reps'),
  ('bear-crawl-knee-taps','Weight & Reps, Time Only'),
  ('bw-squats','Weight & Reps, Time Only'),
  ('hurdler-stretch','Time Only'),
  ('middle-splits','Time Only'),
  ('side-to-side-squat','Weight & Reps, Time Only'),
  ('sit-ups','Weight & Reps'),
  ('hand-walkouts','Weight & Reps'),
  ('single-leg-deadlift','Weight & Reps'),
  ('suicides','Weight & Reps, Time Only'),
  ('high-bounds','Weight & Reps'),
  ('bicep-curl-pyramid','Weight & Reps'),
  ('hammer-curl-drop-set','Weight & Reps'),
  ('dumbbell-upright-row','Weight & Reps'),
  ('dumbbell-bench-squat','Weight & Reps'),
  ('press-ups','Weight & Reps'),
  ('skater-squats','Weight & Reps'),
  ('tricep-dips-bench','Weight & Reps'),
  ('reverse-grip-chest-press','Weight & Reps'),
  ('lower-body-foam-rolling','Weight & Reps, Time Only'),
  ('long-bar-curl','Weight & Reps'),
  ('z-press','Weight & Reps'),
  ('reverse-db-lunges','Weight & Reps'),
  ('db-step-lunges','Weight & Reps'),
  ('barbell-good-mornings','Weight & Reps'),
  ('sumo-deadlift-high-pull','Weight & Reps'),
  ('db-kb-single-leg-deadlift','Weight & Reps'),
  ('db-power-cleans','Weight & Reps'),
  ('ring-body-saw','Weight & Reps'),
  ('kb-db-pullover','Weight & Reps'),
  ('double-kb-squat','Weight & Reps'),
  ('offset-squats','Weight & Reps'),
  ('banded-romanian-deadlift','Weight & Reps'),
  ('kb-deadlift','Weight & Reps'),
  ('leg-extension','Weight & Reps'),
  ('chin-ups-band','Weight & Reps'),
  ('3-way-leg-extension','Weight & Reps'),
  ('reverse-walkouts','Weight & Reps, Time Only'),
  ('box-jumps','Weight & Reps'),
  ('db-chest-press','Weight & Reps'),
  ('weighted-hanging-tuck','Weight & Reps'),
  ('iso-lever-row','Weight & Reps'),
  ('tall-kneeling-kb-tricepm-extension','Weight & Reps'),
  ('dual-kb-swings','Weight & Reps'),
  ('dual-kb-front-rack-drop-lunge','Weight & Reps'),
  ('dual-kb-thrusters','Weight & Reps'),
  ('single-leg-calf-raises','Weight & Reps'),
  ('tall-kneeling-arnold-press','Weight & Reps'),
  ('copenhagen-plank','Weight & Reps, Time Only'),
  ('dual-db-death-march','Weight & Reps'),
  ('dumbbell-glute-bridge-floor','Weight & Reps'),
  ('bench-press','Weight & Reps'),
  ('active-frog-stretch','Weight & Reps, Time Only'),
  ('banded-hip-extension','Weight & Reps'),
  ('ground-pigeon-stretch','Time Only'),
  ('hip-capsule-mobilisation','Time Only'),
  ('overhead-band-squat','Weight & Reps'),
  ('hamstring-closed-chain-lockouts-with-distraction','Time Only'),
  ('tempo-shoulder-press','Weight & Reps'),
  ('single-arm-plate-loaded-bench-press','Weight & Reps'),
  ('alternate-incline-plate-loaded-bench','Weight & Reps'),
  ('dbbb-romanian-deadlifts','Weight & Reps'),
  ('burpee-over-bar','Weight & Reps'),
  ('plate-wood-chops','Weight & Reps'),
  ('dead-stop-skull-crusher','Weight & Reps'),
  ('snatch-grip-deficit-deadlifts','Weight & Reps'),
  ('side-lunges','Weight & Reps'),
  ('incline-twist-curls','Weight & Reps'),
  ('ring-push-ups','Weight & Reps'),
  ('leg-lowerssingle-leg','Weight & Reps'),
  ('cycle-squat-1-14','Weight & Reps'),
  ('dbkb-front-rack-march','Weight & Reps'),
  ('bb-thrusters','Weight & Reps'),
  ('dual-db-front-squats','Weight & Reps'),
  ('basic-glute-mobilisation','Time Only'),
  ('basic-lat-mobilisation','Time Only'),
  ('quad-adductor-stack','Time Only'),
  ('couch-stretch','Time Only'),
  ('seated-adductor-smash','Time Only'),
  ('bent-leg-quad-smash','Time Only'),
  ('air-squats','Weight & Reps, Time Only'),
  ('supinated-chin-ups','Weight & Reps'),
  ('rkc-plank','Weight & Reps, Time Only'),
  ('leg-press-calf-raise','Weight & Reps'),
  ('bw-1-1-2-squats','Weight & Reps'),
  ('bb-front-foot-elevated-split-squats','Weight & Reps'),
  ('bb-strict-press-1-1-2','Weight & Reps'),
  ('lateral-lunges','Weight & Reps, Time Only'),
  ('squat-jumps','Weight & Reps'),
  ('db-skull-crushers','Weight & Reps'),
  ('power-cleans','Weight & Reps'),
  ('dual-db-deadlifts','Weight & Reps'),
  ('prone-pec-stretch','Weight & Reps, Time Only'),
  ('db-z-press','Weight & Reps'),
  ('concentrated-bench-bicep-curl','Weight & Reps'),
  ('thoracic-bridge-w-reach','Weight & Reps'),
  ('burpee-over-rower','Weight & Reps'),
  ('banded-elbow-extension','Time Only'),
  ('posterior-shoulder-capsule-mobilisation','Time Only'),
  ('alternate-get-ups','Weight & Reps'),
  ('straight-arm-pulldown-functional-trainer','Weight & Reps'),
  ('hollow-rocks','Weight & Reps'),
  ('squat-to-stand','Weight & Reps'),
  ('bb-high-pulls','Weight & Reps'),
  ('db-pullover','Weight & Reps'),
  ('single-leg-pike-stretch','Time Only'),
  ('advanced-reverse-crunch','Weight & Reps, Time Only'),
  ('leg-raises','Weight & Reps'),
  ('plank-toe-taps','Weight & Reps, Time Only'),
  ('banded-bully-1','Time Only'),
  ('kb-db-thrusters','Weight & Reps'),
  ('suspension-trainer-bicep-curl','Weight & Reps'),
  ('prone-fly','Weight & Reps'),
  ('incline-chest-fly','Weight & Reps'),
  ('olympic-wall-squat','Time Only'),
  ('zottman-curls','Weight & Reps'),
  ('band-pull-aparts','Weight & Reps'),
  ('90-90-hip-flows','Weight & Reps, Time Only'),
  ('quad-t-spine-rotation','Weight & Reps, Time Only'),
  ('single-leg-negatives-lying-leg-curl','Weight & Reps'),
  ('hack-squat-calf-raises','Weight & Reps'),
  ('single-leg-hack-squat-calf-raises','Weight & Reps'),
  ('tempo-hack-squat','Weight & Reps'),
  ('3-points-rows','Weight & Reps'),
  ('nebula-power-grip-seated-cable-row','Weight & Reps'),
  ('iso-hold-seated-cable-row','Weight & Reps'),
  ('single-arm-cable-rows','Weight & Reps'),
  ('single-arm-iso-chest-press','Weight & Reps'),
  ('global-over-head-extension','Time Only'),
  ('band-tricep-pushdowns','Weight & Reps'),
  ('single-leg-extensions','Weight & Reps'),
  ('tall-kneeling-filly-press','Weight & Reps'),
  ('incline-db-chest-press','Weight & Reps'),
  ('marching-glute-bridge','Weight & Reps'),
  ('dt','Weight & Reps'),
  ('dual-kb-cleans','Weight & Reps'),
  ('oh-walking-lunges','Weight & Reps'),
  ('single-arm-db-bench-press','Weight & Reps'),
  ('db-chest-flyes','Weight & Reps'),
  ('back-rack-drop-lunges','Weight & Reps'),
  ('squat-tuck-jumps','Weight & Reps'),
  ('deficit-snatch-grip-rdl','Weight & Reps'),
  ('bradford-press','Weight & Reps'),
  ('tuck-ups','Weight & Reps'),
  ('future-method-bench-press','Weight & Reps'),
  ('deep-squat-with-rotation','Weight & Reps'),
  ('bb-behind-the-neck-press','Weight & Reps'),
  ('cycle-back-squats','Weight & Reps'),
  ('worlds-greatest-stretch','Weight & Reps, Time Only'),
  ('kb-windmills','Weight & Reps'),
  ('incline-alternate-db-bench-press','Weight & Reps'),
  ('incline-crush-grip-chest-press','Weight & Reps'),
  ('hanging-oblique-crunches','Weight & Reps'),
  ('hanging-knee-tucks','Weight & Reps'),
  ('db-close-arm-floor-press','Weight & Reps'),
  ('bb-upright-rows','Weight & Reps'),
  ('bike-erg','Time Only, Distance & Time, Calories'),
  ('military-press-1-1-4','Weight & Reps'),
  ('scapula-push-ups','Weight & Reps'),
  ('shotguns','Weight & Reps'),
  ('squat-holds','Weight & Reps'),
  ('kb-cycle-squats','Weight & Reps'),
  ('kb-gorilla-rows','Weight & Reps'),
  ('romanian-deadlifts','Weight & Reps'),
  ('box-jump-overs','Weight & Reps'),
  ('bb-push-press','Weight & Reps'),
  ('pike-planks','Weight & Reps, Time Only'),
  ('hang-power-cleans','Weight & Reps'),
  ('bb-strict-press','Weight & Reps'),
  ('heel-flicks','Weight & Reps'),
  ('bb-clusters','Weight & Reps'),
  ('hang-muscle-snatch','Weight & Reps'),
  ('db-bench-press','Weight & Reps'),
  ('bb-bench-press','Weight & Reps'),
  ('bb-floor-press','Weight & Reps'),
  ('negative-chin-ups-band','Weight & Reps'),
  ('hip-openers','Weight & Reps'),
  ('down-dog-holds','Weight & Reps'),
  ('seated-row-machine','Weight & Reps'),
  ('bb-glute-bridge','Weight & Reps'),
  ('bbkb-banded-upright-row','Weight & Reps'),
  ('bandcable-tricep-pushdowns','Weight & Reps'),
  ('theragun-shoulder-chest-mob','Time Only'),
  ('horizontal-adductor-opener','Time Only'),
  ('shoulder-rotator-smash-floss','Time Only'),
  ('reverse-hack-squat','Weight & Reps'),
  ('db-floor-press','Weight & Reps'),
  ('db-strict-press','Weight & Reps'),
  ('oblique-crunches','Weight & Reps'),
  ('lying-leg-curl','Weight & Reps'),
  ('stutter-rep-leg-press','Weight & Reps'),
  ('smith-machine-shrugs','Weight & Reps'),
  ('stairmaster','Time Only, Distance & Time, Calories'),
  ('bulgarian-split-squat-jumps','Weight & Reps'),
  ('landmine-calf-raises','Weight & Reps'),
  ('box-step-ups','Weight & Reps'),
  ('mountain-climbers','Weight & Reps'),
  ('leg-extension-1-1-2','Weight & Reps'),
  ('iso-chest-press','Weight & Reps'),
  ('paused-close-grip-bench-press','Weight & Reps'),
  ('kb-push-ups','Weight & Reps'),
  ('db-walking-lunges','Weight & Reps'),
  ('single-arm-db-thrusters','Weight & Reps'),
  ('seated-db-bent-over-row','Weight & Reps'),
  ('adductor-rock-back','Weight & Reps, Time Only'),
  ('press-up-with-lateral-hand-walk','Weight & Reps'),
  ('bw-glute-bridge','Weight & Reps'),
  ('calf-raises','Weight & Reps'),
  ('db-bent-over-row','Weight & Reps'),
  ('banded-pull-throughs','Weight & Reps'),
  ('how-to-use-the-treadmills','Time Only, Distance & Time, Calories'),
  ('close-grip-bench-press','Weight & Reps'),
  ('groiners','Weight & Reps'),
  ('tfl-mobilisation','Time Only'),
  ('banded-bully-2-extension-bias','Time Only'),
  ('dual-kb-wall-sits','Weight & Reps'),
  ('devils-press-thrusters','Weight & Reps'),
  ('rower','Time Only, Distance & Time, Calories'),
  ('basic-bb-trap-scrub','Time Only'),
  ('alternate-db-snatch','Weight & Reps'),
  ('db-renegade-rows','Weight & Reps'),
  ('ghd-sit-ups','Weight & Reps, Time Only'),
  ('db-split-squat','Weight & Reps'),
  ('sumo-deadlift','Weight & Reps'),
  ('db-step-ups','Weight & Reps'),
  ('narrow-hurdler-stretch','Time Only'),
  ('wide-grip-pull-ups','Weight & Reps'),
  ('db-kb-toe-raised-rdl','Weight & Reps'),
  ('yoga-push-ups','Weight & Reps'),
  ('lying-leg-curl-pyramid','Weight & Reps'),
  ('goblet-1-12-bulgarian-split-squats','Weight & Reps'),
  ('dual-kbdb-snatch','Weight & Reps'),
  ('bb-strict-press-1-12','Weight & Reps'),
  ('stutter-rep-hack-squat','Weight & Reps'),
  ('incline-plate-loaded-chest-press','Weight & Reps'),
  ('shoulder-burns','Weight & Reps'),
  ('bb-bicep-smash','Time Only'),
  ('front-facing-hack-squat','Weight & Reps'),
  ('burpee-over-db','Weight & Reps'),
  ('dual-db-devils-press','Weight & Reps'),
  ('negative-sit-ups','Weight & Reps'),
  ('knee-tucks','Weight & Reps'),
  ('db-single-arm-row','Weight & Reps'),
  ('seated-lateral-raise','Weight & Reps'),
  ('incline-cable-chest-fly','Weight & Reps'),
  ('single-arm-cable-tricep-extension','Weight & Reps'),
  ('rope-tricep-pulldowns','Weight & Reps'),
  ('cable-face-pulls','Weight & Reps'),
  ('rope-straight-arm-pull-downs','Weight & Reps'),
  ('single-arm-rope-tricep-extension','Weight & Reps'),
  ('single-arm-straight-arm-pulldown','Weight & Reps'),
  ('cable-rope-crunches','Weight & Reps'),
  ('iso-lat-pulldown','Weight & Reps'),
  ('nebula-power-grip-lat-pulldown','Weight & Reps'),
  ('close-arm-lat-pulldown','Weight & Reps'),
  ('ring-rows','Weight & Reps'),
  ('inverted-rows','Weight & Reps'),
  ('single-arm-curl-and-press','Weight & Reps'),
  ('back-squats','Weight & Reps'),
  ('sled-push-overview','Weight & Reps'),
  ('suitcase-march','Weight & Reps, Time Only, Distance & Time'),
  ('db-suitcase-deadlifts','Weight & Reps'),
  ('front-dumbbell-raise','Weight & Reps'),
  ('hollow-hold','Weight & Reps, Time Only'),
  ('dumbbell-curl','Weight & Reps'),
  ('leg-press','Weight & Reps'),
  ('overhead-press','Weight & Reps'),
  ('treadmill-run','Time Only, Distance & Time, Calories'),
  ('glute-bridge','Weight & Reps'),
  ('glute-drive-machine','Weight & Reps'),
  ('chest-flye-machine','Weight & Reps'),
  ('reverse-flye-machine','Weight & Reps'),
  ('smith-row-chest-supported-row','Weight & Reps'),
  ('db-hang-high-pull','Weight & Reps'),
  ('kb-plank-pull-throughs','Weight & Reps, Time Only'),
  ('duck-walks','Weight & Reps'),
  ('db-prone-rows','Weight & Reps'),
  ('prone-flyes','Weight & Reps'),
  ('prone-shrugs','Weight & Reps'),
  ('spider-curls','Weight & Reps'),
  ('tarzan-pull-ups','Weight & Reps'),
  ('3-way-leg-press','Weight & Reps'),
  ('leg-press-drop-set','Weight & Reps'),
  ('db-preacher-curl','Weight & Reps'),
  ('face-pull-functional-trainer','Weight & Reps'),
  ('tall-box-jumps','Weight & Reps'),
  ('posterior-fly','Weight & Reps'),
  ('lower-body-mobility-work','Weight & Reps'),
  ('burpee-tuck-jumps','Weight & Reps'),
  ('reverse-grip-bent-over-row','Weight & Reps'),
  ('suspension-trainer-reverse-fly','Weight & Reps'),
  ('pike-plank-elbows','Weight & Reps, Time Only'),
  ('pike-plank-hands','Weight & Reps, Time Only'),
  ('feet-elevated-side-plank-hip-taps','Weight & Reps, Time Only'),
  ('lateral-lat-pulldown','Weight & Reps'),
  ('behind-the-neck-pulldowns','Weight & Reps'),
  ('smith-row-rear-supported-row','Weight & Reps'),
  ('preacher-curl','Weight & Reps'),
  ('reverse-preacher-curl','Weight & Reps'),
  ('banded-press-ups','Weight & Reps'),
  ('basic-t-spine-smash','Time Only'),
  ('ql-smash','Time Only'),
  ('bw-calf-raises','Weight & Reps'),
  ('diagonal-crunches','Weight & Reps'),
  ('db-kb-push-press','Weight & Reps'),
  ('barbell-box-squat','Weight & Reps'),
  ('dumbbell-push-press','Weight & Reps'),
  ('overhead-band-reverse-lunge','Weight & Reps'),
  ('pike-push-ups','Weight & Reps, Time Only'),
  ('single-leg-rdl','Weight & Reps'),
  ('band-dislocates','Weight & Reps, Time Only'),
  ('reach-rotate','Weight & Reps, Time Only'),
  ('frog-rocks','Weight & Reps, Time Only'),
  ('bird-dogs','Weight & Reps, Time Only'),
  ('dead-bug','Weight & Reps, Time Only'),
  ('reverse-crunches','Weight & Reps, Time Only'),
  ('dorsal-raises','Weight & Reps, Time Only'),
  ('seated-row-machine-mid-handle','Weight & Reps'),
  ('seated-row-machine-low-handle','Weight & Reps'),
  ('barbell-single-leg-deadlift','Weight & Reps'),
  ('single-arm-band-rows','Weight & Reps'),
  ('leg-lowers-single-leg','Weight & Reps'),
  ('upright-row-functional-trainer','Weight & Reps'),
  ('cable-reverse-flye-functional-trainer','Weight & Reps'),
  ('cable-pallof-press','Weight & Reps'),
  ('high-to-low-cable-fly','Weight & Reps'),
  ('low-to-high-cable-fly','Weight & Reps'),
  ('shoulder-extension-stretch','Time Only'),
  ('incline-close-arm-bench-press','Weight & Reps'),
  ('ring-tuck-ups','Weight & Reps'),
  ('russian-twists','Weight & Reps'),
  ('sa-turkish-sit-ups','Weight & Reps'),
  ('kb-front-rack-march','Weight & Reps'),
  ('pike-box-push-ups','Weight & Reps'),
  ('diamond-frog-stretch','Weight & Reps, Time Only'),
  ('lizard-stretch','Time Only'),
  ('curtsey-lunges','Weight & Reps'),
  ('iron-cross','Weight & Reps, Time Only'),
  ('pigeon-to-hip-flexor','Weight & Reps, Time Only'),
  ('lat-pulldowns','Weight & Reps'),
  ('cable-tricep-extension','Weight & Reps'),
  ('box-step-overs','Weight & Reps'),
  ('rear-foot-elevated-bb-split-squat','Weight & Reps'),
  ('incline-bb-bench-press','Weight & Reps'),
  ('lateral-box-jump-overs','Weight & Reps'),
  ('burpee-box-jumps','Weight & Reps'),
  ('bb-toe-raised-rdl','Weight & Reps'),
  ('db-b-stance-romanian-deadlift','Weight & Reps'),
  ('skater-jumps','Weight & Reps'),
  ('dual-kb-switch-cossack-squats','Weight & Reps'),
  ('wall-sits','Weight & Reps'),
  ('wall-balls','Weight & Reps'),
  ('banded-push-ups','Weight & Reps'),
  ('deficit-deadlifts','Weight & Reps'),
  ('hand-supported-single-leg-rdl','Weight & Reps'),
  ('single-leg-v-ups','Weight & Reps'),
  ('piriformis-stretch','Weight & Reps'),
  ('burpee-ball-slams','Weight & Reps'),
  ('tall-kneeling-landmine-press','Weight & Reps'),
  ('banded-facepulls','Weight & Reps'),
  ('turkish-get-ups','Weight & Reps'),
  ('prisoner-squat','Weight & Reps'),
  ('crush-grip-db-curls','Weight & Reps'),
  ('close-arm-press-ups','Weight & Reps'),
  ('kb-romanian-deadlift','Weight & Reps'),
  ('sa-push-press','Weight & Reps'),
  ('sprint-on-the-spot','Weight & Reps'),
  ('press-up-variations','Weight & Reps, Time Only'),
  ('inchworms','Weight & Reps, Time Only'),
  ('prone-scorpions','Weight & Reps'),
  ('clam-shells','Weight & Reps, Time Only'),
  ('slow-mountain-climbers','Weight & Reps, Time Only'),
  ('hollow-sit-ups','Weight & Reps'),
  ('burpee-db-step-ups','Weight & Reps'),
  ('deep-squat-hold','Weight & Reps'),
  ('bb-front-squats','Weight & Reps'),
  ('single-arm-floor-press','Weight & Reps'),
  ('burpee-to-plate','Weight & Reps'),
  ('curved-treadmill','Time Only, Distance & Time, Calories'),
  ('nordic-hamstring-curl','Weight & Reps'),
  ('hyper-extensions','Weight & Reps'),
  ('seated-band-rows','Weight & Reps'),
  ('side-plank','Time Only'),
  ('banded-kb-swings','Weight & Reps'),
  ('goblet-1-1-2-bulgarian-split-squats','Weight & Reps'),
  ('front-rack-reverse-lunges','Weight & Reps'),
  ('dual-db-snatch','Weight & Reps'),
  ('burpee-lateral-hops','Weight & Reps'),
  ('bb-complex','Weight & Reps'),
  ('incline-alternate-db-chest-press','Weight & Reps'),
  ('rolling-tricep-press','Weight & Reps'),
  ('band-tricep-push-down','Weight & Reps'),
  ('dual-front-rack-carry','Weight & Reps'),
  ('bb-clean-and-press','Weight & Reps'),
  ('basic-lower-back-mobilisation','Time Only'),
  ('barbell-glute-bridge-floor','Weight & Reps'),
  ('dumbell-shrugs','Weight & Reps'),
  ('concentrated-bicep-curls','Weight & Reps'),
  ('air-bike','Time Only, Distance & Time, Calories'),
  ('side-to-side-ball-slams','Weight & Reps'),
  ('db-tricep-kickbacks','Weight & Reps'),
  ('1-2-kneeling-bottoms-up-kb-press','Weight & Reps'),
  ('cycle-squat-1-1-4','Weight & Reps'),
  ('dual-kb-push-press','Weight & Reps'),
  ('bb-squat-cleans','Weight & Reps'),
  ('banded-wide-grip-pull-ups','Weight & Reps'),
  ('single-leg-glute-bridge','Weight & Reps'),
  ('zz-fail-test-exercise','Weight & Reps'),
  ('seated-cable-rows','Weight & Reps'),
  ('hamstring-planks','Weight & Reps, Time Only'),
  ('hard-style-plank','Weight & Reps, Time Only'),
  ('plank','Weight & Reps, Time Only'),
  ('shoulder-extension-bridge','Weight & Reps'),
  ('kb-sumo-squat-jumps','Weight & Reps'),
  ('sa-oh-reverse-lunge','Weight & Reps'),
  ('kang-squats','Weight & Reps'),
  ('smith-machine-narrow-grip-bench-press','Weight & Reps'),
  ('smith-machine-stutter-rep-bench-press','Weight & Reps'),
  ('smith-machine-z-press','Weight & Reps'),
  ('smith-machine-squats','Weight & Reps'),
  ('smith-machine-split-squat','Weight & Reps'),
  ('pull-ups','Weight & Reps'),
  ('tuck-holds','Weight & Reps'),
  ('side-plank-hip-taps','Weight & Reps, Time Only'),
  ('dual-kb-cross-body-walking-lunges','Weight & Reps'),
  ('bicycle-crunches','Weight & Reps, Time Only'),
  ('american-kb-swings','Weight & Reps'),
  ('curl-to-press','Weight & Reps'),
  ('arnold-press','Weight & Reps'),
  ('dumbbell-single-leg-deadlifts','Weight & Reps'),
  ('single-leg-glute-bridge-bench','Weight & Reps'),
  ('barbell-glute-bridge-bench','Weight & Reps'),
  ('close-grip-bench-1-12','Weight & Reps'),
  ('side-lateral-seam-mobilisation','Time Only'),
  ('how-to-use-the-versastriders','Time Only, Distance & Time, Calories'),
  ('push-jerks','Weight & Reps'),
  ('front-rack-foot-elevated-reverse-lunge','Weight & Reps'),
  ('deep-squat-hold-with-plate','Weight & Reps'),
  ('seated-shoulder-press','Weight & Reps'),
  ('side-plank-banded-row','Weight & Reps'),
  ('dead-hang','Weight & Reps'),
  ('bw-windmills','Weight & Reps'),
  ('farmers-walk','Weight & Reps, Distance & Time'),
  ('ball-slams','Weight & Reps'),
  ('weighted-crunches','Weight & Reps'),
  ('teddy-bear-to-v-sit','Weight & Reps'),
  ('db-swimmer-curls','Weight & Reps'),
  ('bear-squat-pull-through','Weight & Reps'),
  ('sa-suitcase-deadlift','Weight & Reps'),
  ('posterior-neck-mobilisation','Time Only'),
  ('alternate-db-push-press','Weight & Reps'),
  ('stutter-rep-close-arm-db-press','Weight & Reps'),
  ('ez-bar-curls','Weight & Reps'),
  ('single-arm-db-preacher-curl','Weight & Reps'),
  ('assisted-pull-up','Weight & Reps'),
  ('assisted-dips','Weight & Reps'),
  ('seated-chest-press','Weight & Reps'),
  ('narrow-grip-chest-press-machine','Weight & Reps'),
  ('adductor-machine','Weight & Reps'),
  ('abductor-machine','Weight & Reps'),
  ('smith-machine-tempo-bench-press','Weight & Reps'),
  ('bent-over-row-functional-trainer','Weight & Reps'),
  ('single-arm-cable-curl','Weight & Reps'),
  ('smith-machine-bench-press','Weight & Reps'),
  ('ski-erg','Time Only, Distance & Time, Calories'),
  ('bb-quad-smash','Time Only'),
  ('ankle-plantar-flexion','Weight & Reps, Time Only'),
  ('ankle-dorsi-flexion','Weight & Reps, Time Only'),
  ('tuck-rocks','Weight & Reps'),
  ('kb-banded-upright-row','Weight & Reps'),
  ('offset-kb-reverse-lunge','Weight & Reps'),
  ('squat-thrusts','Weight & Reps, Time Only'),
  ('kb-db-high-pull','Weight & Reps'),
  ('plate-front-raise','Weight & Reps'),
  ('90-90-split-pullovers','Weight & Reps'),
  ('band-bicep-curls','Weight & Reps'),
  ('db-cleans','Weight & Reps'),
  ('tempo-leg-press','Weight & Reps'),
  ('band-face-pull-to-press','Weight & Reps'),
  ('db-band-overhead-tricep-extension','Weight & Reps'),
  ('plank-reach','Weight & Reps, Time Only'),
  ('toes-out-calf-raise','Weight & Reps'),
  ('see-saw-rows','Weight & Reps'),
  ('cossack-squat-hold','Weight & Reps, Time Only'),
  ('lower-thoracic-mobilisation','Time Only'),
  ('basic-quad-smash','Time Only'),
  ('alternate-v-ups','Weight & Reps, Time Only'),
  ('sprinter-bridge-crunches','Weight & Reps'),
  ('plyo-press-ups','Weight & Reps'),
  ('incline-db-bench-1-1-2s','Weight & Reps'),
  ('bear-hold-shoulder-taps','Weight & Reps, Time Only'),
  ('scapula-pull-ups','Weight & Reps'),
  ('pike-stretch','Time Only'),
  ('seiza-stretch','Time Only'),
  ('standing-toe-stretch','Time Only'),
  ('elevated-cat-stretch','Weight & Reps, Time Only'),
  ('shoulder-capsule-stretch','Time Only'),
  ('high-knees','Weight & Reps'),
  ('single-leg-glute-bridge-no-weight','Weight & Reps'),
  ('glute-bridge-no-weight','Weight & Reps'),
  ('pulse-squats','Weight & Reps'),
  ('reverse-lunges','Weight & Reps'),
  ('lunges','Weight & Reps'),
  ('power-squats','Weight & Reps'),
  ('burpee-lateral-box-jumps','Weight & Reps'),
  ('jumping-jacks','Weight & Reps, Time Only'),
  ('overhead-kb-march','Weight & Reps, Time Only'),
  ('1-1-4-kb-db-squats','Weight & Reps'),
  ('cat-camel','Weight & Reps, Time Only'),
  ('1-2-kneeling-band-pulldown','Weight & Reps'),
  ('kbdb-gorilla-rows','Weight & Reps'),
  ('dumbbell-glute-bridge-bench','Weight & Reps'),
  ('standing-kneeling-pallof-press','Weight & Reps, Time Only'),
  ('leg-lower-alternate','Weight & Reps, Time Only'),
  ('rear-foot-elevated-single-leg-romanian-deadlift','Weight & Reps'),
  ('t-spine-mobilisation','Time Only'),
  ('elevated-pigeon-stretch','Time Only'),
  ('pigeon-stretch','Weight & Reps, Time Only'),
  ('standing-hamstring-stretch','Weight & Reps'),
  ('toes-to-bar','Weight & Reps'),
  ('db-lateral-raises','Weight & Reps'),
  ('butterfly-sit-ups','Weight & Reps, Time Only'),
  ('side-plank-rotations','Weight & Reps, Time Only'),
  ('prisoner-lunges','Weight & Reps'),
  ('banded-over-head-press','Weight & Reps'),
  ('wide-mountain-climbers','Weight & Reps'),
  ('banded-bent-over-row','Weight & Reps'),
  ('banded-overhead-distraction','Time Only'),
  ('banded-bully-3-punch-bully','Time Only'),
  ('bb-bent-over-row','Weight & Reps'),
  ('plank-push-ups','Weight & Reps'),
  ('banded-good-mornings','Weight & Reps'),
  ('front-foot-elevated-jumping-lunges','Weight & Reps'),
  ('tricep-dips','Weight & Reps'),
  ('bb-z-press','Weight & Reps'),
  ('mixed-rack-carries','Weight & Reps, Distance & Time'),
  ('prayer-holds','Weight & Reps'),
  ('3d-band-pull-aparts','Weight & Reps'),
  ('front-to-lat-raise','Weight & Reps'),
  ('crunches','Weight & Reps'),
  ('burpee-db-cleans','Weight & Reps'),
  ('landmine-plank-row','Weight & Reps'),
  ('banded-donkey-kicks','Weight & Reps'),
  ('seated-row-machine-high-handle','Weight & Reps'),
  ('tall-kneeling-kb-tricep-extension','Weight & Reps'),
  ('bw-glute-bridge-on-bench','Weight & Reps'),
  ('db-kb-glute-bridge','Weight & Reps'),
  ('lat-stretch','Time Only'),
  ('pancake-stretch','Time Only'),
  ('blackburns','Weight & Reps, Time Only'),
  ('spiderman-lunges','Weight & Reps, Time Only'),
  ('single-leg-lateral-jumps','Weight & Reps, Time Only'),
  ('kb-swings','Weight & Reps'),
  ('front-rack-walking-lunges','Weight & Reps'),
  ('bw-1-12-squats','Weight & Reps'),
  ('military-press-1-14','Weight & Reps'),
  ('defecit-snatch-grip-rdl','Weight & Reps'),
  ('table-top-iso-hold','Weight & Reps, Time Only'),
  ('banded-thrusters','Weight & Reps'),
  ('single-arm-db-dt','Weight & Reps'),
  ('band-front-to-overhead-raise','Weight & Reps'),
  ('spiderman-lunge-with-rotation','Weight & Reps, Time Only'),
  ('rear-foot-elevated-hip-flexor-stretch','Weight & Reps, Time Only'),
  ('deadmill-sprints','Time Only, Distance & Time, Calories'),
  ('scott-press','Weight & Reps'),
  ('burpee-box-step-ups','Weight & Reps'),
  ('chainsaw-rows','Weight & Reps'),
  ('hammer-curl','Weight & Reps'),
  ('rope-curls-functional-trainer','Weight & Reps'),
  ('ez-bar-curl-functional-trainer','Weight & Reps'),
  ('ez-bar-tricep-extension-functional-trainer','Weight & Reps'),
  ('db-pendlay-rows','Weight & Reps'),
  ('90-degree-crunches','Weight & Reps, Time Only'),
  ('v-ups','Weight & Reps, Time Only'),
  ('jumping-lunges','Weight & Reps, Time Only'),
  ('straight-arm-step-burpees','Weight & Reps'),
  ('bw-renegade-row','Weight & Reps'),
  ('bw-single-leg-rdl','Weight & Reps'),
  ('landmine-single-arm-row','Weight & Reps'),
  ('tall-plank-knee-to-elbow','Weight & Reps, Time Only'),
  ('bb-bicep-curls','Weight & Reps'),
  ('bb-reverse-curls','Weight & Reps'),
  ('db-reverse-flyes','Weight & Reps'),
  ('goblet-bulgarian-split-squats','Weight & Reps'),
  ('close-grip-bench-1-1-2','Weight & Reps'),
  ('pendulum-lunges','Weight & Reps'),
  ('tall-plank','Weight & Reps, Time Only'),
  ('deficit-snatch-grip-deadlifts','Weight & Reps'),
  ('single-leg-glute-bridge-floor','Weight & Reps'),
  ('close-arm-dumbbell-press','Weight & Reps'),
  ('dumbbell-multi-directional-lunges','Weight & Reps'),
  ('db-bulgarian-split-squat','Weight & Reps'),
  ('stability-ball-hamstring-curl','Weight & Reps'),
  ('pendlay-row','Weight & Reps'),
  ('sumo-squat','Weight & Reps'),
  ('close-arm-bench-press','Weight & Reps'),
  ('hand-release-press-ups','Weight & Reps, Time Only'),
  ('romanian-deadlift-row-combo','Weight & Reps'),
  ('hand-walkout-into-press-up','Weight & Reps'),
  ('1-1-4-bw-squats','Weight & Reps'),
  ('banded-glute-bridge','Weight & Reps'),
  ('db-kb-glute-bridge-on-bench','Weight & Reps'),
  ('plank-shoulder-taps','Weight & Reps, Time Only'),
  ('alternate-iso-chest-press','Weight & Reps'),
  ('single-leg-lying-hamstring-curl','Weight & Reps'),
  ('star-jumps','Weight & Reps'),
  ('banded-hamstring-curls','Weight & Reps'),
  ('around-the-world-lunges','Weight & Reps'),
  ('barbell-split-squat','Weight & Reps'),
  ('hammer-kb-curls','Weight & Reps'),
  ('split-squats','Weight & Reps'),
  ('goblet-squats','Weight & Reps'),
  ('quad-rock-backs','Weight & Reps, Time Only'),
  ('cossack-squats','Weight & Reps, Time Only'),
  ('down-dog-mountain-climber','Weight & Reps, Time Only'),
  ('single-arm-row','Weight & Reps'),
  ('stutter-rep-close-arm-bench-press','Weight & Reps'),
  ('banded-face-pulls','Weight & Reps'),
  ('dumbbell-chest-fly','Weight & Reps'),
  ('upper-body-foam-rolling','Weight & Reps, Time Only'),
  ('banded-hip-mobility','Weight & Reps'),
  ('back-mobility-routine','Weight & Reps'),
  ('single-arm-tricep-kickback','Weight & Reps'),
  ('dumbbell-over-head-tricep-extension','Weight & Reps'),
  ('db-side-lunge','Weight & Reps'),
  ('seated-calf-raise','Weight & Reps'),
  ('standing-calf-raise','Weight & Reps'),
  ('suspension-trainer-row','Weight & Reps, Time Only')
) as v(id, tt)
where e.id = v.id;

notify pgrst, 'reload schema';